/**
 * CR 331 (GT Comments 4, "Expense log" sheet) - GreenTech's chart of accounts for expenses. A
 * heading (code ending in 00) groups the accounts under it and cannot be chosen; the rest are what
 * an expense line is booked to. 5xxx are direct project costs (COGS), 6xxx corporate expenses.
 * Only GreenTech staff see or set the category; an outside login never does.
 */
export type ExpenseCategory = { code: string; name: string; type: "COGS" | "Expense"; heading: boolean };

const RAW: Array<[string, string]> = [
  ["5000", "DIRECT PROJECT COSTS"],
  ["5100", "Design & Engineering"],
  ["5110", "Design & Engineering Services"],
  ["5120", "Architectural Services"],
  ["5130", "Mechanical Engineering"],
  ["5140", "Electrical Engineering"],
  ["5150", "Civil / Structural Engineering"],
  ["5160", "Surveying / Site Investigation"],
  ["5170", "Geotechnical Services"],
  ["5180", "Technical Consulting"],
  ["5200", "Materials & Equipment"],
  ["5210", "General Materials & Supplies"],
  ["5220", "Process / Treatment Equipment"],
  ["5230", "HVAC Equipment"],
  ["5240", "Electrical Equipment & Materials"],
  ["5250", "BAS / BMS / Controls"],
  ["5260", "Piping / Valves / Fittings"],
  ["5270", "Instrumentation"],
  ["5280", "Spare Parts"],
  ["5290", "Tools & Consumables"],
  ["5300", "Subcontractors & Project Labor"],
  ["5310", "General Subcontractor"],
  ["5320", "Civil / Construction Subcontractor"],
  ["5330", "Mechanical Subcontractor"],
  ["5340", "Electrical Subcontractor"],
  ["5350", "HVAC Subcontractor"],
  ["5360", "WTP / WWTP / STP Subcontractor"],
  ["5370", "BAS / BMS / Controls Subcontractor"],
  ["5380", "Local / Temporary Labor"],
  ["5390", "Technician / Specialist Services"],
  ["5400", "Freight & Logistics"],
  ["5410", "Freight & Shipping"],
  ["5420", "Local Transportation / Delivery"],
  ["5430", "Customs & Duties"],
  ["5440", "Customs Broker / Clearance"],
  ["5450", "Freight Forwarding"],
  ["5460", "Packing / Crating"],
  ["5470", "Warehousing / Storage"],
  ["5480", "Cargo / Marine Insurance"],
  ["5490", "Demurrage / Detention / Port Fees"],
  ["5500", "Project Travel & Mobilization"],
  ["5510", "Airfare"],
  ["5520", "Hotel / Accommodation"],
  ["5530", "Meals / Per Diem"],
  ["5540", "Ground Transportation"],
  ["5550", "Visa / Work Permit"],
  ["5560", "Mobilization"],
  ["5570", "Demobilization"],
  ["5580", "Other Travel"],
  ["5600", "Construction & Site Operations"],
  ["5610", "Equipment Rental"],
  ["5620", "Crane / Rigging / Heavy Lift"],
  ["5630", "Excavation / Earthwork"],
  ["5640", "Concrete / Civil Works"],
  ["5650", "Installation Services"],
  ["5660", "Temporary Facilities / Services"],
  ["5670", "Site Utilities"],
  ["5680", "Site Security Services"],
  ["5690", "Cleaning / Site Support"],
  ["5700", "Testing, Commissioning & O&M"],
  ["5710", "Laboratory Testing"],
  ["5720", "Testing & Commissioning"],
  ["5730", "Start-Up Services"],
  ["5740", "Inspection Services"],
  ["5750", "Factory Acceptance Testing (FAT)"],
  ["5760", "Client / O&M Training"],
  ["5770", "O&M / Maintenance Services"],
  ["5780", "Chemicals / Treatment Supplies"],
  ["5790", "Tanker / Temporary Water Service"],
  ["5800", "Project Insurance, Bonds & Compliance"],
  ["5810", "DBA Insurance"],
  ["5820", "Project-Specific Insurance"],
  ["5830", "Performance Bond"],
  ["5840", "Payment Bond"],
  ["5850", "Bid Bond"],
  ["5860", "Other Bond / Guarantee Fees"],
  ["5870", "Project Permits & Government Fees"],
  ["5880", "Project Registration / Licensing"],
  ["5900", "Project Management & Administration"],
  ["5910", "Project Management"],
  ["5920", "Project Administration"],
  ["5930", "Site / Project Office Rent"],
  ["5940", "Site / Project Office Supplies"],
  ["5950", "Project Communications / Internet"],
  ["5960", "Project Printing / Documentation"],
  ["5970", "Project Courier / Postage"],
  ["5980", "Project-Specific Software / Subscriptions"],
  ["5990", "Other Direct Project Cost"],
  ["6000", "CORPORATE / OPERATING EXPENSES"],
  ["6100", "Payroll & Employee Costs"],
  ["6110", "Salaries & Wages"],
  ["6120", "Payroll Taxes"],
  ["6130", "Employee Benefits"],
  ["6140", "Health Insurance"],
  ["6150", "Retirement / Employer Contributions"],
  ["6160", "Recruiting"],
  ["6170", "Employee Training & Development"],
  ["6180", "Bonuses"],
  ["6200", "Professional Services"],
  ["6210", "Accounting / Bookkeeping"],
  ["6220", "Legal Services"],
  ["6230", "Business / Management Consulting"],
  ["6240", "IT / Technology Services"],
  ["6250", "Proposal / Business Development Support"],
  ["6260", "Other Professional Services"],
  ["6300", "Office & Administration"],
  ["6310", "Corporate Office Rent"],
  ["6320", "Corporate Office Supplies"],
  ["6330", "Corporate Utilities"],
  ["6340", "Corporate Telephone & Internet"],
  ["6350", "Corporate Software & Subscriptions"],
  ["6360", "Corporate Printing & Postage"],
  ["6370", "Computer / IT Supplies"],
  ["6380", "Office Repairs & Maintenance"],
  ["6390", "Employee Meetings / Events"],
  ["6400", "Corporate Travel & Business Development"],
  ["6410", "Corporate Airfare"],
  ["6420", "Corporate Hotel / Accommodation"],
  ["6430", "Corporate Meals"],
  ["6440", "Corporate Ground Transportation"],
  ["6450", "Business Development"],
  ["6460", "Marketing & Advertising"],
  ["6470", "Conferences / Events"],
  ["6480", "Proposal / Bid Expenses"],
  ["6500", "Corporate Insurance"],
  ["6510", "General Liability Insurance"],
  ["6520", "Workers' Compensation Insurance"],
  ["6530", "Professional Liability / E&O"],
  ["6540", "Commercial Auto Insurance"],
  ["6550", "Cyber Insurance"],
  ["6560", "Umbrella / Excess Insurance"],
  ["6570", "Other Corporate Insurance"],
  ["6600", "Registrations, Licenses & Compliance"],
  ["6610", "State / Local Business Registration"],
  ["6620", "Business Licenses"],
  ["6630", "Government Registration / Compliance"],
  ["6640", "Corporate Certifications"],
  ["6650", "Annual Filing / Registered Agent Fees"],
  ["6700", "Banking & Financial Expenses"],
  ["6710", "Bank Service Charges"],
  ["6720", "Wire Transfer Fees"],
  ["6730", "Credit Card / Merchant Fees"],
  ["6740", "Letter of Credit / Bank Guarantee Fees"],
  ["6750", "Interest Expense"],
  ["6760", "Loan / Financing Fees"],
  ["6800", "Taxes, Vehicles & Other Corporate Expenses"],
  ["6810", "Business Taxes & Government Fees"],
  ["6820", "Property / Personal Property Tax"],
  ["6830", "Corporate Vehicle Expenses"],
  ["6840", "Vehicle Fuel"],
  ["6850", "Vehicle Repairs & Maintenance"],
  ["6860", "Parking & Tolls"],
  ["6870", "Donations / Contributions"],
  ["6880", "Miscellaneous Corporate Expense"],
];

export const EXPENSE_CATEGORIES: ExpenseCategory[] = RAW.map(([code, name]) => ({
  code, name, type: code.startsWith("5") ? "COGS" : "Expense", heading: code.endsWith("00"),
}));

const SELECTABLE = new Set(EXPENSE_CATEGORIES.filter((c) => !c.heading).map((c) => c.code));
/** A code that can be booked to, or "" (a heading or anything else is dropped). */
export const cleanCategory = (v: unknown): string => (SELECTABLE.has(String(v ?? "")) ? String(v) : "");
